<template>
    <SectionTopBanner />
    <div class="container">
        <div class="row">
            <div class="col-12" v-for="(faq, index) in faqs" :key="index">
                <div class="accordion accordion-flush" style="background-color: var(--bg-primary);"
                    id="accordionFlushExample">
                    <div class="accordion-item my-2 border-0 ">
                        <h2 class="accordion-header border">
                            <button class="accordion-button text-white collapsed border-start border-4" type="button"
                                data-bs-toggle="collapse" :data-bs-target="'#flush-collapseOne' + index"
                                aria-expanded="false" :aria-controls="'flush-collapseOne' + index"
                                style="border-color: var(--bg-secondary) !important; background-color: var(--bg-primary)">
                                <span class="me-2">Q{{ index + 1 }}.</span> {{ faq.question }}
                            </button>
                        </h2>
                        <div :id="'flush-collapseOne' + index" class="accordion-collapse collapse border-0"
                            data-bs-parent="#accordionFlushExample">
                            <div class="accordion-body text-start">{{ faq.answer }}</div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- <div class="wh-60 rounded-circle position-fixed  bg-success px-3 py-1" data-bs-toggle="modal"
        data-bs-target="#exampleModal" style="bottom: 20px; right: 5px;">
        <i class="bi bi-phone fs-2 text-white"></i>
    </div> -->
    <FaqFormSection />

</template>


<script>
import SectionTopBanner from '@/components/SectionTopBanner.vue'
import FaqFormSection from '@/components/FaqFormSection.vue'
export default {
    name: "FaqPage",
    components: {
        SectionTopBanner,
        FaqFormSection,
    },
    data() {
        return {
            faqs: [
                {
                    "question": "What are the benefits of installing solar panels?",
                    "answer": "Solar panels help reduce electricity bills, decrease carbon footprint, and provide a renewable source of energy. In India, solar power also allows users to take advantage of government subsidies and incentives."
                },
                {
                    "question": "How much can I save on electricity bills with solar panels?",
                    "answer": "By installing solar panels, you can save up to 70-90% on your electricity bills, depending on the size of your solar system and energy consumption."
                },
                {
                    "question": "Does the government offer any subsidies for solar panel installations?",
                    "answer": "Yes, the Indian government offers subsidies for residential solar panel installations under various state and national schemes to encourage solar energy adoption."
                },
                {
                    "question": "How long do solar panels last?",
                    "answer": "Solar panels typically last between 25 to 30 years with minimal maintenance, providing reliable energy over their lifespan."
                },
                {
                    "question": "Can solar panels work during cloudy or rainy days?",
                    "answer": "Yes, solar panels can still generate power on cloudy or rainy days, though the efficiency may be reduced compared to sunny days."
                },
                {
                    "question": "Do I need a battery for my solar panel system?",
                    "answer": "A battery is not necessary but can be useful for storing excess energy generated by your solar panels, allowing you to use solar power during the night or during power outages."
                },
                {
                    "question": "What maintenance is required for solar panels?",
                    "answer": "Solar panels require minimal maintenance. Regular cleaning to remove dust and debris and occasional system checks are recommended to ensure optimal performance."
                },
                {
                    "question": "How long does it take to install solar panels?",
                    "answer": "The installation of solar panels typically takes 1 to 3 days, depending on the size of the system and the complexity of the installation."
                }
            ],
            searchTerm: '',
            activeTabIndex: 0
        };
    },
};
</script>

<style scoped>
.form-control {
    box-shadow: none !important;
}

.accordion-button:not(.collapsed) {
    color: white !important;
    background-color: var(--bg-secondary) !important;
    border-color: 4px solid var(--bg-primary) !important;
    box-shadow: none !important;
}

.accordion-button:focus {
    z-index: 3;
    outline: 0;
    box-shadow: none !important;
}

/* Add any necessary styling here */
</style>
